POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "Abhirup Das",
  "username": "abhirup",
  "email": "abhirup@gmail.com",
  "password": "1234"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "abhirup@gmail.com",
  "password": "1234"
}

### 
GET http://localhost:3000/get_user_and_profile
Content-Type: application/json

{
  "token": "efca697a83c91bab8fb5dd80d8f9d67ad6b9694ff4b4559ba4596d764e1e1c06"
}

###
POST http://localhost:5050/update_profile_data
Content-Type: application/json

{
 "token": "74ad629bdad8a03f9f30ee077bb02bb6513509cff971af025e1de6425091380d",

  "bio": "Passionate MERN Stack Developer",
  "currentPost": "Backend Developer",
  "education": [
    {
      "school": "Nadia College",
      "degree": "B.Sc",
      "fildOfStudy": "Computer Science"
    }
  ],
  "pastWork": [
    {
      "company": "Tech Corp",
      "position": "Intern",
      "years": "6 months"
    }
  ]

}

###
GET http://localhost:3000/user/get_all_users
Content-Type: application/json